Repository ClassBridge/ClassBridge-BE, pull requests merged in 2024-05, with the labels that each got.

#5 Docs: Update issue templates
  .github/ISSUE_TEMPLATE/issue--bug.md
  .github/ISSUE_TEMPLATE/issue--feature.md
Labels: docs

#21 feat(common methods): add common methods like global exception and hello api
  build.gradle
  src/main/java/com/linked/classbridge/config/JpaAuditingConfiguration.java
  src/main/java/com/linked/classbridge/config/SwaggerConfig.java
  src/main/java/com/linked/classbridge/controller/HelloController.java
  src/main/java/com/linked/classbridge/domain/BaseEntity.java
  src/main/java/com/linked/classbridge/domain/Hello.java
  src/main/java/com/linked/classbridge/dto/HelloDto.java
  src/main/java/com/linked/classbridge/dto/SuccessResponse.java
  src/main/java/com/linked/classbridge/exception/GlobalExceptionHandler.java
  src/main/java/com/linked/classbridge/exception/RestApiException.java
  src/main/java/com/linked/classbridge/repository/HelloRepository.java
  src/main/java/com/linked/classbridge/service/HelloService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/main/resources/application-local.yml
  src/main/resources/logback-spring.xml
Labels: docs, feat, chore

#23 feat(review) : add Review Creation, Update, and Deletion functionality
  .gitignore
  build.gradle
  src/main/java/com/linked/classbridge/config/S3Config.java
  src/main/java/com/linked/classbridge/controller/ReviewController.java
  src/main/java/com/linked/classbridge/dataloader/InitDataLoader.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/domain/Review.java
  src/main/java/com/linked/classbridge/domain/ReviewImage.java
  src/main/java/com/linked/classbridge/domain/User.java
  src/main/java/com/linked/classbridge/dto/review/DeleteReviewResponse.java
  src/main/java/com/linked/classbridge/dto/review/RegisterReviewDto.java
  src/main/java/com/linked/classbridge/dto/review/UpdateReviewDto.java
  src/main/java/com/linked/classbridge/exception/GlobalExceptionHandler.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/repository/OneDayClassRepository.java
  src/main/java/com/linked/classbridge/repository/ReviewImageRepository.java
  src/main/java/com/linked/classbridge/repository/ReviewRepository.java
  src/main/java/com/linked/classbridge/repository/UserRepository.java
  src/main/java/com/linked/classbridge/service/LessonService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/service/S3Service.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/main/resources/application-local.yml
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
Labels: feat, test, chore
