Repository ClassBridge/ClassBridge-BE, pull requests merged in 2024-06, with the labels that each got.

#30 feat(review) : add getting review detail functionality and add test code about Creation of review
  src/main/java/com/linked/classbridge/config/WebConfig.java
  src/main/java/com/linked/classbridge/controller/OneDayClassController.java
  src/main/java/com/linked/classbridge/controller/ReviewController.java
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/domain/Review.java
  src/main/java/com/linked/classbridge/domain/User.java
  src/main/java/com/linked/classbridge/dto/review/GetReviewResponse.java
  src/main/java/com/linked/classbridge/repository/ReviewRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/controller/UserControllerTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: feat, test

#38 Feature/#10 add class and get class list, get class
  build.gradle
  src/main/java/com/linked/classbridge/config/KakaoMapConfig.java
  src/main/java/com/linked/classbridge/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/linked/classbridge/config/RestTemplateConfig.java
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/dataloader/InitDataLoader.java
  src/main/java/com/linked/classbridge/domain/Category.java
  src/main/java/com/linked/classbridge/domain/ClassFAQ.java
  src/main/java/com/linked/classbridge/domain/ClassImage.java
  src/main/java/com/linked/classbridge/domain/ClassTag.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/domain/Review.java
  src/main/java/com/linked/classbridge/domain/User.java
  src/main/java/com/linked/classbridge/dto/kakaoMapDto/KakaoAddress.java
  src/main/java/com/linked/classbridge/dto/kakaoMapDto/KakaoMapResponse.java
  src/main/java/com/linked/classbridge/dto/kakaoMapDto/KakaoRoadAddress.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassFAQDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassImageDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassTagDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassUpdateDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/DayOfWeekListCreator.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/LessonDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/RepeatClassDto.java
  src/main/java/com/linked/classbridge/dto/review/GetReviewResponse.java
  src/main/java/com/linked/classbridge/repository/CategoryRepository.java
  src/main/java/com/linked/classbridge/repository/ClassFAQRepository.java
  src/main/java/com/linked/classbridge/repository/ClassImageRepository.java
  src/main/java/com/linked/classbridge/repository/ClassTagRepository.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/repository/OneDayClassRepository.java
  src/main/java/com/linked/classbridge/service/KakaoMapService.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/service/S3Service.java
  src/main/java/com/linked/classbridge/type/CategoryType.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/controller/UserControllerTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: fix, docs, feat, refactor, chore

#41 Feature/#10 update class and delete class
  .gitignore
  build.gradle
  src/main/java/com/linked/classbridge/config/SecurityConfig.java
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/domain/ClassFAQ.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassFAQDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassUpdateDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/LessonDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/RepeatClassDto.java
  src/main/java/com/linked/classbridge/repository/ClassFAQRepository.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: fix, feat, refactor, test, chore

#47 refactor: create repeat lesson refactoring
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/RepeatClassDto.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
Labels: refactor

#50 Feature/#42 faq
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassFAQDto.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
  src/test/java/com/linked/classbridge/service/OneDayClassServiceTest.java
Labels: fix, feat, style, refactor, test

#55 Feature/#43 tag
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassTagDto.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/test/java/com/linked/classbridge/service/OneDayClassServiceTest.java
Labels: feat, style, refactor, test

#57 feat(chat) : add read chat and send receipt functionality
  src/main/java/com/linked/classbridge/config/WebSocketConfig.java
  src/main/java/com/linked/classbridge/controller/WebSocketController.java
  src/main/java/com/linked/classbridge/domain/UserChatRoom.java
  src/main/java/com/linked/classbridge/dto/chat/ReadReceipt.java
  src/main/java/com/linked/classbridge/dto/chat/ReadReceiptList.java
  src/main/java/com/linked/classbridge/repository/ChatRoomRepository.java
  src/main/java/com/linked/classbridge/service/ChatRoomService.java
  src/main/java/com/linked/classbridge/service/ChatService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/test/java/com/linked/classbridge/service/ChatRoomServiceTest.java
  src/test/java/com/linked/classbridge/service/ChatServiceTest.java
Labels: feat, test

#58 Feature/#56 lesson
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/LessonDto.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/LessonService.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/service/OneDayClassServiceTest.java
Labels: fix, feat, style, refactor, test

#66 Feature/#62 create wish
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/domain/Wish.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/user/WishDto.java
  src/main/java/com/linked/classbridge/repository/OneDayClassRepository.java
  src/main/java/com/linked/classbridge/repository/WishRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/test/java/com/linked/classbridge/service/UserServiceTest.java
Labels: fix, feat, refactor, test

#67 Feature/#61 Save search related oneDayClassDocument
  build.gradle
  src/main/java/com/linked/classbridge/ClassBridgeApplication.java
  src/main/java/com/linked/classbridge/config/AWSRequestSigningApacheInterceptor.java
  src/main/java/com/linked/classbridge/config/OpenSearchConfig.java
  src/main/java/com/linked/classbridge/config/OpenSearchRestConfig.java
  src/main/java/com/linked/classbridge/domain/document/OneDayClassDocument.java
  src/main/java/com/linked/classbridge/repository/OneDayClassDocumentRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/resources/elasticsearch/mapping.json
  src/main/resources/elasticsearch/setting.json
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
  src/test/java/com/linked/classbridge/service/OneDayClassServiceTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
  src/test/java/com/linked/classbridge/service/UserServiceTest.java
Labels: fix, feat, style, refactor, test, chore

#69 feat(chat): add read chat message functionality
  src/main/java/com/linked/classbridge/config/WebSocketConfig.java
  src/main/java/com/linked/classbridge/controller/ChatRoomController.java
  src/main/java/com/linked/classbridge/controller/ReviewController.java
  src/main/java/com/linked/classbridge/controller/WebSocketController.java
  src/main/java/com/linked/classbridge/domain/ChatRoom.java
  src/main/java/com/linked/classbridge/domain/UserChatRoom.java
  src/main/java/com/linked/classbridge/dto/chat/ChatRoomDto.java
  src/main/java/com/linked/classbridge/dto/chat/ChatRoomUnreadCountInfoDto.java
  src/main/java/com/linked/classbridge/dto/chat/ReadReceipt.java
  src/main/java/com/linked/classbridge/dto/chat/ReadReceiptList.java
  src/main/java/com/linked/classbridge/repository/ChatMessageRepository.java
  src/main/java/com/linked/classbridge/repository/ChatRoomRepository.java
  src/main/java/com/linked/classbridge/repository/UserChatRoomRepository.java
  src/main/java/com/linked/classbridge/service/ChatRoomService.java
  src/main/java/com/linked/classbridge/service/ChatService.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/java/com/linked/classbridge/service/chat/ChatMessageService.java
  src/main/java/com/linked/classbridge/service/chat/ChatRoomService.java
  src/main/java/com/linked/classbridge/service/chat/ChatService.java
  src/main/java/com/linked/classbridge/service/chat/MessageSendingService.java
  src/main/java/com/linked/classbridge/service/chat/UserChatRoomService.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/main/java/com/linked/classbridge/websocket/StompHandler.java
  src/test/java/com/linked/classbridge/controller/ChatRoomControllerTest.java
  src/test/java/com/linked/classbridge/service/ChatRoomServiceTest.java
  src/test/java/com/linked/classbridge/service/ChatServiceTest.java
  src/test/java/com/linked/classbridge/service/chat/ChatMessageServiceTest.java
  src/test/java/com/linked/classbridge/service/chat/ChatRoomServiceTest.java
  src/test/java/com/linked/classbridge/service/chat/ChatServiceTest.java
  src/test/java/com/linked/classbridge/service/chat/MessageSendingServiceTest.java
  src/test/java/com/linked/classbridge/service/chat/UserChatRoomServiceTest.java
Labels: fix, feat, refactor, test

#72 test(review) : fix review test code
  src/main/java/com/linked/classbridge/config/SecurityConfig.java
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
  src/test/java/com/linked/classbridge/controller/UserControllerTest.java
Labels: test

#74 Feature/#73 change chatroom list return
  build.gradle
  src/main/java/com/linked/classbridge/config/OpenSearchConfig.java
  src/main/java/com/linked/classbridge/controller/ChatRoomController.java
  src/main/java/com/linked/classbridge/dto/chat/ChatRoomDto.java
  src/main/java/com/linked/classbridge/dto/chat/GetChatRoomsResponse.java
  src/main/java/com/linked/classbridge/service/chat/ChatService.java
  src/test/java/com/linked/classbridge/controller/ChatRoomControllerTest.java
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/service/chat/ChatServiceTest.java
Labels: feat, test

#79 Chore/application local
  src/main/java/com/linked/classbridge/config/OpenSearchConfig.java
  src/main/java/com/linked/classbridge/config/OpenSearchRestConfig.java
  src/main/java/com/linked/classbridge/config/S3Config.java
  src/main/resources/application-local.yml
Labels: refactor, chore

#80 Feat/application-local add kakaomap config
  src/main/resources/application-local.yml
Labels: chore

#78 Feature/#61 search
  src/main/java/com/linked/classbridge/config/OpenSearchConfig.java
  src/main/java/com/linked/classbridge/controller/HelloController.java
  src/main/java/com/linked/classbridge/controller/OneDayClassController.java
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/domain/Hello.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/document/OneDayClassDocument.java
  src/main/java/com/linked/classbridge/dto/HelloDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassSearchDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/LessonDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/LessonDtoDetail.java
  src/main/java/com/linked/classbridge/repository/HelloRepository.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/HelloService.java
  src/main/java/com/linked/classbridge/service/KakaoMapService.java
  src/main/java/com/linked/classbridge/service/LessonService.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/LocationType.java
  src/main/java/com/linked/classbridge/type/OrderType.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
  src/main/resources/elasticsearch/mapping.json
  src/main/resources/elasticsearch/setting.json
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
  src/test/java/com/linked/classbridge/service/OneDayClassServiceTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: fix, feat, style, refactor, test

#83 fix: 리뷰 테스트 코드 수정
  src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: test

#97 fix(review) : fix update review image logic
  src/main/java/com/linked/classbridge/config/SecurityConfig.java
  src/main/java/com/linked/classbridge/controller/ReviewController.java
  src/main/java/com/linked/classbridge/domain/Lesson.java
  src/main/java/com/linked/classbridge/domain/OneDayClass.java
  src/main/java/com/linked/classbridge/domain/ReviewImage.java
  src/main/java/com/linked/classbridge/dto/review/GetReviewImageDto.java
  src/main/java/com/linked/classbridge/dto/review/GetReviewResponse.java
  src/main/java/com/linked/classbridge/dto/review/RegisterReviewDto.java
  src/main/java/com/linked/classbridge/dto/review/UpdateReviewDto.java
  src/main/java/com/linked/classbridge/dto/review/UpdateReviewImageDto.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
  src/main/java/com/linked/classbridge/service/S3Service.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ImageUpdateAction.java
  src/main/resources/application-local.yml
  src/test/java/com/linked/classbridge/ClassBridgeApplicationTests.java
  src/test/java/com/linked/classbridge/controller/OneDayClassControllerTest.java
  src/test/java/com/linked/classbridge/controller/ReviewControllerTest.java
  src/test/java/com/linked/classbridge/controller/TutorControllerTest.java
  src/test/java/com/linked/classbridge/controller/UserControllerTest.java
  src/test/java/com/linked/classbridge/service/ReviewServiceTest.java
Labels: fix, feat, refactor, test

#108 Refactor/#82 class images
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/domain/document/OneDayClassDocument.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassSearchDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassUpdateDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/UpdateClassImageDto.java
  src/main/java/com/linked/classbridge/repository/ClassImageRepository.java
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/type/ErrorCode.java
  src/main/java/com/linked/classbridge/type/ImageUpdateAction.java
  src/main/resources/elasticsearch/mapping.json
  src/main/resources/elasticsearch/setting.json
  src/test/java/com/linked/classbridge/controller/TutorClassControllerTest.java
Labels: refactor

#112 Fix/#111 lazy loading class
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassSearchDto.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
Labels: fix

#115 Refactor/ add totalReviews in OneDayClassDocument and address to address 1,2,3 in ClassDto
  src/main/java/com/linked/classbridge/domain/document/OneDayClassDocument.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassDto.java
  src/main/java/com/linked/classbridge/dto/oneDayClass/ClassSearchDto.java
  src/main/resources/elasticsearch/mapping.json
Labels: fix, refactor

#119 refactor: add roles for tutor and user
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/controller/UserController.java
Labels: refactor

#127 refactor: add columns set studentCount, averageAge, totalAge, maleCou…
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
Labels: fix, refactor

#132 Feat/#131 search class order end date
  src/main/java/com/linked/classbridge/controller/TutorController.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
Labels: fix, feat

#139 Feat/#138 get user
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/main/java/com/linked/classbridge/dto/user/UserInfoDto.java
  src/main/java/com/linked/classbridge/service/UserService.java
  src/main/java/com/linked/classbridge/type/ResponseMessage.java
Labels: feat

#142 refactor: wish delete with classId
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/main/java/com/linked/classbridge/repository/WishRepository.java
  src/main/java/com/linked/classbridge/service/UserService.java
Labels: refactor

#144 Develop -> release merge
  src/main/java/com/linked/classbridge/controller/UserController.java
  src/main/java/com/linked/classbridge/repository/WishRepository.java
  src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
  src/main/java/com/linked/classbridge/service/UserService.java
Labels: deploy

#148 refactor: add SuccessReservationDto
  src/main/java/com/linked/classbridge/controller/PaymentController.java
  src/main/java/com/linked/classbridge/dto/reservation/SuccessReservationDto.java
  src/main/java/com/linked/classbridge/repository/ReservationRepository.java
  src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
Labels: refactor

#149 Develop -> release merge
  src/main/java/com/linked/classbridge/controller/PaymentController.java
  src/main/java/com/linked/classbridge/dto/reservation/SuccessReservationDto.java
  src/main/java/com/linked/classbridge/repository/ReservationRepository.java
  src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
Labels: deploy

#151 refactor: add url reservationId and classId
  src/main/java/com/linked/classbridge/controller/PaymentController.java
  src/main/java/com/linked/classbridge/repository/ReservationRepository.java
  src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
Labels: refactor

#152 Develop -> release merge
  src/main/java/com/linked/classbridge/controller/HomeController.java
  src/main/java/com/linked/classbridge/controller/PaymentController.java
  src/main/java/com/linked/classbridge/repository/ReservationRepository.java
  src/main/java/com/linked/classbridge/service/KakaoPaymentService.java
Labels: deploy

#153 fix: set total reviews in oneDayClassDocument
  src/main/java/com/linked/classbridge/repository/LessonRepository.java
  src/main/java/com/linked/classbridge/service/OneDayClassService.java
  src/main/java/com/linked/classbridge/service/ReviewService.java
Labels: fix, refactor
